"""RNS interface preset management for chatx5 config generation."""

import time

from chatx5.core.rns_interfaces.config import render_rns_config
from chatx5.core.rns_interfaces.iface_list import (
    add_interface,
    configured_serial_port,
    delete_interface,
    hub_tcp_client_active,
    lan_transport_hub_policy,
    normalize_interface_list,
    remove_tcp_client_to_host,
    set_primary_lan_transport,
    tcp_client_target_is_local,
    tcp_client_target_warning,
    update_interface,
)
from chatx5.core.rns_interfaces.presets import (
    ANDROID_DEFAULT_INTERFACE_LIST,
    ANDROID_SERIAL_PERMISSION_HINT,
    DEFAULT_INTERFACE_LIST,
    INTERFACE_PRESETS,
    SERIAL_ACCESS_GROUPS,
    SERIAL_BAUD_RATES,
    SERIAL_DEFAULT_BAUD,
    SERIAL_PERMISSION_HINT,
    android_standalone_needs_udp,
    default_interface_list,
    standalone_needs_udp,
)
from chatx5.core.rns_interfaces.runtime_common import (
    _finalize_rns_interface,
    _register_hot_rns_interface,
)
from chatx5.core.rns_interfaces.serial_ports import (
    list_android_usb_serial_ports,
    list_serial_ports,
    serial_permission_hint_for_process,
    serial_port_accessible,
    serial_port_available,
    serial_port_status,
    serial_runtime_active,
    serial_skip_reason,
    user_has_serial_group_access,
)
from chatx5.core.rns_interfaces.serial_runtime import (
    dedupe_serial_interfaces,
    find_serial_interface,
    hot_add_serial_interface,
    prune_dead_serial_interfaces,
    register_serial_hot_add_callback,
    remove_serial_interfaces,
    serial_interface_is_ready,
)
from chatx5.core.rns_interfaces.settings import (
    configured_serial_enabled,
    configured_tcp_lan_enabled,
    configured_tcp_lan_listen,
    configured_udp_lan_enabled,
    lan_discovery_configured,
    load_settings_interfaces,
)
from chatx5.core.rns_interfaces.summary import summarize_rns_interfaces
from chatx5.core.rns_interfaces.tcp_iface import (
    ensure_runtime_serial,
    ensure_runtime_tcp_client,
    ensure_runtime_tcp_hub,
    ensure_runtime_tcp_lan_server,
    ensure_tcp_client_to_peer,
    find_tcp_server_interface,
    hot_add_tcp_client_interface,
    hot_add_tcp_server_interface,
    normalize_hub_listen_interfaces,
    remove_tcp_client_interfaces,
    remove_tcp_hub_listeners,
    remove_tcp_listeners_on_port,
    tcp_client_interface_online,
    tcp_server_interface_online,
    tcp_server_interfaces_online,
)

__all__ = [
    "_finalize_rns_interface",
    "_register_hot_rns_interface",
    "ANDROID_DEFAULT_INTERFACE_LIST",
    "ANDROID_SERIAL_PERMISSION_HINT",
    "DEFAULT_INTERFACE_LIST",
    "INTERFACE_PRESETS",
    "SERIAL_ACCESS_GROUPS",
    "SERIAL_BAUD_RATES",
    "SERIAL_DEFAULT_BAUD",
    "SERIAL_PERMISSION_HINT",
    "add_interface",
    "android_standalone_needs_udp",
    "configured_serial_enabled",
    "configured_serial_port",
    "configured_tcp_lan_enabled",
    "configured_tcp_lan_listen",
    "configured_udp_lan_enabled",
    "dedupe_serial_interfaces",
    "default_interface_list",
    "delete_interface",
    "ensure_runtime_serial",
    "ensure_runtime_tcp_client",
    "ensure_runtime_tcp_hub",
    "ensure_runtime_tcp_lan_server",
    "ensure_tcp_client_to_peer",
    "find_serial_interface",
    "find_tcp_server_interface",
    "hot_add_serial_interface",
    "hot_add_tcp_client_interface",
    "hot_add_tcp_server_interface",
    "hub_tcp_client_active",
    "lan_discovery_configured",
    "lan_transport_hub_policy",
    "list_android_usb_serial_ports",
    "list_serial_ports",
    "load_settings_interfaces",
    "normalize_hub_listen_interfaces",
    "normalize_interface_list",
    "prune_dead_serial_interfaces",
    "register_serial_hot_add_callback",
    "remove_serial_interfaces",
    "remove_tcp_client_interfaces",
    "remove_tcp_client_to_host",
    "remove_tcp_hub_listeners",
    "remove_tcp_listeners_on_port",
    "render_rns_config",
    "serial_interface_is_ready",
    "serial_permission_hint_for_process",
    "serial_port_accessible",
    "serial_port_available",
    "serial_port_status",
    "serial_runtime_active",
    "serial_skip_reason",
    "set_primary_lan_transport",
    "standalone_needs_udp",
    "summarize_rns_interfaces",
    "tcp_client_interface_online",
    "tcp_client_target_is_local",
    "tcp_client_target_warning",
    "tcp_server_interface_online",
    "tcp_server_interfaces_online",
    "time",
    "update_interface",
    "user_has_serial_group_access",
]
