"""Timeouts, message types, and shared constants for the messaging layer."""

APP_NAME = "chatx5"
LINK_CONNECT_TIMEOUT_S = 12
ANDROID_LINK_CONNECT_TIMEOUT_S = 14
FAILOVER_CONNECT_TIMEOUT_S = 16
LINK_CONNECT_POLL_S = 0.05
IDENTITY_WAIT_TIMEOUT_S = 12
ANDROID_IDENTITY_WAIT_TIMEOUT_S = 16
SERIAL_IDENTITY_WAIT_TIMEOUT_S = 35
SERIAL_PATH_PRIME_TIMEOUT_S = 28
SERIAL_ANNOUNCE_BURST_COUNT = 1
SERIAL_ANNOUNCE_BURST_INTERVAL_S = 0
SERIAL_CONNECT_PRIME_INTERVAL_S = 3.0
SERIAL_LINK_CONNECT_TIMEOUT_S = 22
SERIAL_INBOUND_FIRST_WAIT_S = 4
SERIAL_INBOUND_WAIT_S = 12
REVERSE_CONNECT_WAIT_S = 10
ANDROID_REVERSE_CONNECT_WAIT_S = 12
INITIATOR_INBOUND_WAIT_S = 8
ANDROID_INITIATOR_INBOUND_WAIT_S = 10
QUICK_OUTBOUND_TIMEOUT_S = 6
HTTP_WAKE_TIMEOUT_S = 1.5
LINK_FAILOVER_GRACE_S = 30
LINK_STALE_FAILOVER_IDLE_S = 90
SESSION_RECONNECT_MIN_IDLE_S = 18
DUAL_PATH_RECONNECT_MIN_IDLE_S = 4
DUAL_PATH_FAILOVER_COOLDOWN_S = 8
DUAL_PATH_DISCONNECTED_COOLDOWN_S = 4
SERIAL_SPEED_MARGIN = 1.15
PEER_LAN_UNREACHABLE_TTL_S = 90
RECEIPT_FAILOVER_TIMEOUT_S = 30
RECEIPT_FAILOVER_MIN_PENDING = 2
MAX_CONCURRENT_RECEIVES = 2
QUEUE_RETRY_INTERVAL_S = 5
QUEUE_DRAIN_DELAY_S = 1.0
QUEUE_RECEIPT_TIMEOUT_S = 30

_NO_COMPRESS_SUFFIXES = frozenset({
    ".apk", ".zip", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".mp4", ".mkv", ".webm", ".mov", ".m4v",
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".heic",
    ".mp3", ".ogg", ".opus", ".wav", ".flac", ".aac",
    ".pdf", ".deb", ".rpm", ".jar", ".aar",
})

MESSAGE_TYPE_TEXT = "text"
MESSAGE_TYPE_FILE = "file"
MESSAGE_TYPE_IMAGE = "image"
MESSAGE_TYPE_VOICE = "voice"
MESSAGE_TYPE_VIDEO = "video"
MESSAGE_TYPE_EMOJI = "emoji"
MESSAGE_TYPE_LONGTEXT = "longtext"
MESSAGE_TYPE_SHARE_BROWSE = "share_browse"
MESSAGE_TYPE_LAN_HTTP = "__lan_http_offer"
MESSAGE_TYPE_TRANSFER_CANCEL = "__transfer_cancel"
LAN_HTTP_MIN_BYTES = 512 * 1024
LAN_HTTP_CHUNK = 1024 * 1024
HUB_GROUP_PEER = "__hub_group__"